version: '3.8'
services:
  unitest-api:
    build: .
    container_name: unitest-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: unless-stopped
